title: "Release_<dd>_<mm>_<yyyy>"
labels: ["Project Releases"]
body:
  - type: markdown
    attributes:
      value: |
        **Welcome to the Release Discussion!**
        Please fill out the details below
  - type: input
    id: deployment_url
    attributes:
      label: Deployment URL
      description: "Provide the URL to the deployment workflow"
      placeholder: https://example.com
    validations:
      required: true
  - type: input
    id: deployment_steps
    attributes:
      label: Deployment Runbook Steps
      description: "Enter the path or link to the deployment runbook steps"
      placeholder: "/docs/runbooks/release_dd_mm_yyyy.md"
    validations:
      required: true
