title: "Release mm-dd-yyyy"
labels: ["Project Releases"]
body:
  - type: markdown
    attributes:
      value: |
        **Welcome to the Release Discussion!**
        "Please fill out the details below"
  - type: dropdown
    attributes:
      label: What is the type of release?
      description: Provides detail of the release type
      options:
        - Major Release
        - Minor Release
        - Hotfix
      default: Major Release 
    validations:
      required: true
  - type: textarea
    id: deployment_url
    attributes:
      label: Deployment URL
      description: "Provide the URL to the deployment workflow"
      value: |
        ## Deployment URL
      
        [Deployment URL](https://example.com)
    validations:
      required: true
  - type: textarea
    id: deployment_steps
    attributes:
      label: Deployment Runbook Steps
      description: "Enter the path or link to the deployment runbook steps"
      value: |
        ## Deployment Runbook Steps
        
        [Deployment Runbook Steps](/docs/runbooks/release_mm_dd_yyyy)
    validations:
      required: true
