title: "Release_dd_mm_yyyy"
labels: ["Project Releases"]
body:
  - type: markdown
    attributes:
      value: |
        **Welcome to the Release Discussion!**
        Please fill out the details below
  - type: textarea
    id: deployment_url
    attributes:
      label: Deployment URL
      description: "Provide the URL to the deployment workflow"
      placeholder: |
        [Deployment URL](https://example.com)
    validations:
      required: true
  - type: textarea
    id: deployment_steps
    attributes:
      label: Deployment Runbook Steps
      description: "Enter the path or link to the deployment runbook steps"
      placeholder: |
        [Deployment Runbook Steps](/docs/runbooks/release_dd_mm_yyyy.md)
    validations:
      required: true
