title: "Release mm-dd-yyyy"
labels: ["Project Releases"]
body:
  - type: markdown
    attributes:
      value: |
        ## Release Discussion
      
        **Welcome to the official Discussion thread for this Release!**
  - type: dropdown
    attributes:
      label: Release Type
      description: Select the appropriate type of release
      options:
        - Major Release
        - Minor Release
        - Hotfix 
    validations:
      required: true
  - type: textarea
    id: deployment_info
    attributes:
      label: Deployment Information
      description: |
        "Provide the relevant deployment details, including links to documentation and workflows." 
      value: |
        ## Related Documentation 
        
        [Post/Pre Deployment Steps](/docs/runbooks/release_mm_dd_yyyy)

        ## Deployment Workflow
         
        [Release Deployment](https://example.com)
    validations:
      required: true
  - type: textarea
    id: deployment_url
    attributes:
      label: Deployment URL
      description: "Provide the deployment link. You can use Markdown link syntax."
      placeholder: "[Release Deployment](https://your-link-here.com)"
      render: markdown
    validations:
      required: true
  
