name: Code Optimization Request
description: Request to Optimize existing code
title: "Optimize {Component/Class Name}"
assignees:
  - olusogoogunleye
labels: [code-optimization]
body:
  - type: input
    id: optimization_summary
    attributes:
      label: Summary
      description: "What is the purpose of this optimization?"
      placeholder: "Example: Improve the SOQL query efficiency in AccountDataService to reduce governor limit usage."
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Task priority
      description: How important is the optimization?
      options:
        - Highest
        - High
        - Moderate
        - Low
    validations:
      required: true
  - type: input
    id: completion_date
    attributes:
      label: Expected Completion Date
      description: "Specify expected available time"
      placeholder: "mm-dd-yyyy"
    validations:
      required: true
  - type: checkboxes
    id: duplicate_check
    attributes:
      label: Confirmation
      description: Confirm you have verified that this optimization request does not already exist.
      options:
        - label: "I have searched existing issues and did not find a duplicate."
          required: true
